Repository react8jo/react-team, pull requests merged in 2024-04, with the labels that each got.

#15 [Feat] 프록시 서버 사용하여 api 불러오기
  src/components/MainPage/Banner/Banner.jsx
  src/hooks/temp.js
  src/hooks/useBookList.js
  src/services/api.js
  src/setupProxy.js
Labels: feat

#32 [Feat] AppLayout 만들기
  src/components/common/Footer/Footer.jsx
  src/components/common/Footer/footer.styled.js
  src/layout/AppLayout.jsx
  src/layout/appLayout.styled.js
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/mainPage.styled.js
  src/router/Router.jsx
Labels: feat

#33 [Feat] 데이터 없음 작업
  package-lock.json
  package.json
  src/components/common/Nodata/Nodata.jsx
  src/components/common/Nodata/nodata.styled.js
Labels: feat

#35 Feat/banner
  src/components/MainPage/Banner/Banner.jsx
  src/components/MainPage/Banner/NewBookCarousel/NewBookCarousel.jsx
  src/components/MainPage/Banner/NewBookCarousel/newBookCarousel.styled.js
  src/components/MainPage/Banner/banner.styled.js
  src/hooks/useBookList.js
Labels: feat

#38 [Modify] prettier 수정 및 캐러셀 순서 교체
  src/components/MainPage/Banner/Banner.jsx
  src/components/MainPage/Banner/BlogBestSellerCarousel/BlogBestSellerCarousel.jsx
  src/components/MainPage/Banner/NewBookCarousel/newBookCarousel.styled.js
  src/components/MainPage/Banner/banner.styled.js
  src/hooks/useBookList.js
Labels: enhancement

#40 [Feat] 베스트셀러, 추천, 신간 슬라이드 추가
  package-lock.json
  package.json
  src/App.js
  src/components/MainPage/Banner/Banner.jsx
  src/components/MainPage/BestsellerBook/BestsellerBook.jsx
  src/components/MainPage/BestsellerBook/BestsellerBook.style.css
  src/components/MainPage/BestsellerBook/BestsellerBookCard.jsx
  src/components/MainPage/BestsellerBook/BestsellerBookCard.style.css
  src/components/MainPage/BestsellerBook/BestsellerBookSlider.jsx
  src/components/MainPage/BestsellerBook/BestsellerBookSlider.style.css
  src/components/MainPage/ChoiceBook/ChoiceBook.jsx
  src/components/MainPage/ChoiceBook/ChoiceBook.style.css
  src/components/MainPage/ChoiceBook/ChoiceBookCard.jsx
  src/components/MainPage/ChoiceBook/ChoiceBookCard.style.css
  src/components/MainPage/ChoiceBook/ChoiceBookSlider.jsx
  src/components/MainPage/ChoiceBook/ChoiceBookSlider.style.css
  src/components/MainPage/NewBook/NewBook.jsx
  src/components/MainPage/NewBook/NewBook.style.css
  src/components/MainPage/NewBook/NewBookCard.jsx
  src/components/MainPage/NewBook/NewBookCard.style.css
  src/components/MainPage/NewBook/NewBookSlider.jsx
  src/components/MainPage/NewBook/NewBookSlider.style.css
  src/hooks/useBookList.js
  src/pages/MainPage/MainPage.jsx
  src/services/api.js
Labels: feat

#41 [Modify] 구조 수정
  package-lock.json
  src/assets/style/globalStyle.styled.js
  src/components/MainPage/Banner/BlogBestSellerCarousel/blogBestSellerCarousel.styled.js
  src/components/MainPage/Banner/NewBookCarousel/NewBookCarousel.jsx
  src/components/MainPage/Banner/NewBookCarousel/newBookCarousel.styled.js
  src/components/MainPage/Banner/banner.styled.js
  src/pages/MainPage/MainPage.jsx
  src/router/Router.jsx
Labels: bug

#43 [Feat] 메인 슬라이드에서 디테일페이지로 이동
  src/components/MainPage/BestsellerBook/BestsellerBook.jsx
  src/components/MainPage/BestsellerBook/BestsellerBookCard.jsx
  src/components/MainPage/BestsellerBook/bestsellerBook.styled.js
  src/components/MainPage/BestsellerBook/bestsellerBookCard.styled.js
  src/components/MainPage/BestsellerBook/bestsellerBookSlider.styled.js
  src/components/MainPage/ChoiceBook/ChoiceBook.jsx
  src/components/MainPage/ChoiceBook/ChoiceBookCard.jsx
  src/components/MainPage/ChoiceBook/ChoiceBookSlider.jsx
  src/components/MainPage/NewBook/NewBook.jsx
  src/components/MainPage/NewBook/NewBookCard.jsx
  src/components/MainPage/NewBook/NewBookSlider.jsx
  src/router/Router.jsx
Labels: feat

#45 Feat/footer
  src/assets/images/icon-github.png
  src/components/common/Footer/Footer.jsx
  src/components/common/Footer/footer.styled.js
Labels: feat

#47 [Modify] 필터 페이지랑 라우터 수정, [Feat] isbn으로 detail 페이지 navigate
  src/components/MainPage/Banner/BlogBestSellerCarousel/BlogBestSellerCarousel.jsx
  src/components/MainPage/Banner/BlogBestSellerCarousel/blogBestSellerCarousel.styled.js
  src/components/MainPage/Banner/NewBookCarousel/NewBookCarousel.jsx
  src/pages/FilteredPage/FilteredPage.jsx
  src/router/Router.jsx
Labels: bug

#60 Jiyunetlify
  .env
  package-lock.json
  package.json
  public/_redirects
  src/components/FilteredPage/BookCard.jsx
  src/components/FilteredPage/bookCard.styled.js
  src/components/ResultPage/BookCard.jsx
  src/pages/ResultPage/ResultPage.jsx
  src/services/api.js
Labels: bug

#63 [Feat]광고배너만들기
  package-lock.json
  package.json
  src/assets/images/cover-1984.jpeg
  src/assets/images/cover-hp.jpeg
  src/assets/images/cover-prideandprejudice.jpeg
  src/assets/style/globalStyle.styled.js
  src/components/MainPage/AdBanner/AdBanner.jsx
  src/components/MainPage/AdBanner/adBanner.styled.js
  src/pages/MainPage/MainPage.jsx
Labels: feat

#70 [Modify] cart and payment
  src/components/common/Popup/Popup.jsx
  src/components/common/Popup/popup.styled.js
  src/pages/CartPage/CartPage.jsx
  src/pages/CartPage/CartPage.styled.js
  src/pages/PaymentPage/PaymentPage.jsx
  src/pages/PaymentPage/PaymentPage.styled.js
Labels: enhancement

#71 Feat/jiyunmobile
  src/assets/style/globalStyle.styled.js
  src/components/MainPage/Banner/BlogBestSellerCarousel/BlogBestSellerCarousel.jsx
  src/components/MainPage/Banner/BlogBestSellerCarousel/blogBestSellerCarousel.styled.js
  src/components/MainPage/Banner/NewBookCarousel/NewBookCarousel.jsx
  src/components/MainPage/Banner/NewBookCarousel/newBookCarousel.styled.js
Labels: feat

#77 Modify/style
  src/components/MainPage/AdBanner/AdBanner.jsx
  src/components/MainPage/AdBanner/adBanner.styled.js
  src/components/MainPage/Banner/Banner.jsx
  src/components/MainPage/Banner/BlogBestSellerCarousel/BlogBestSellerCarousel.jsx
  src/components/MainPage/Banner/BlogBestSellerCarousel/blogBestSellerCarousel.styled.js
  src/components/MainPage/Banner/NewBookCarousel/newBookCarousel.styled.js
  src/components/MainPage/Banner/banner.styled.js
  src/constants/color.js
Labels: enhancement

#78 [Modify] 메인슬라이드 디자인 수정
  src/components/MainPage/BestsellerBook/BestsellerBook.jsx
  src/components/MainPage/BestsellerBook/BestsellerBookSlider.jsx
  src/components/MainPage/BestsellerBook/bestsellerBook.styled.js
  src/components/MainPage/BestsellerBook/bestsellerBookCard.styled.js
  src/components/MainPage/BestsellerBook/bestsellerBookSlider.styled.js
  src/components/MainPage/ChoiceBook/ChoiceBook.jsx
  src/components/MainPage/ChoiceBook/ChoiceBook.styled.js
  src/components/MainPage/ChoiceBook/ChoiceBookCard.jsx
  src/components/MainPage/ChoiceBook/ChoiceBookCard.styled.js
  src/components/MainPage/ChoiceBook/ChoiceBookSlider.jsx
  src/components/MainPage/ChoiceBook/ChoiceBookSlider.styled.js
  src/components/MainPage/NewBook/NewBook.jsx
  src/components/MainPage/NewBook/NewBookCard.styled.js
  src/components/MainPage/NewBook/NewBookSlider.jsx
  src/components/MainPage/NewBook/NewBookSlider.styled.js
Labels: feat

#79 [Modify] 버튼 컴포넌트 추가
  src/components/ResultPage/SearchBookCard.jsx
  src/components/ResultPage/SearchBookCard.styled.js
  src/components/common/Header/Header.jsx
  src/components/common/Header/header.styled.js
  src/pages/FilteredPage/Pagination.css
  src/pages/ResultPage/ResultPage.jsx
  src/pages/ResultPage/ResultPage.style.css
  src/pages/ResultPage/ResultPage.styled.js
Labels: enhancement

#84 [Modify] 페이지네이션 className 반영, BookCard hover 추가
  src/components/ResultPage/SearchBookCard.jsx
  src/components/ResultPage/SearchBookCard.styled.js
  src/pages/ResultPage/ResultPage.jsx
Labels: enhancement

#87 [Modify] 이미지 사이즈 변경, top 버튼 추가
  src/components/ResultPage/SearchBookCard.styled.js
  src/pages/ResultPage/ResultPage.jsx
Labels: enhancement

#88 Feat/jiyunfavicon
  public/favicon.ico
  public/index.html
  src/components/MainPage/Banner/NewBookCarousel/NewBookCarousel.jsx
  src/components/MainPage/Banner/NewBookCarousel/newBookCarousel.styled.js
  src/components/MainPage/Banner/banner.styled.js
Labels: bug

#91 [Modify] 돋보기 아이콘 크기 수정
  src/components/MainPage/Banner/NewBookCarousel/newBookCarousel.styled.js
  src/components/MainPage/Banner/banner.styled.js
  src/components/common/Header/header.styled.js
Labels: bug

#92 Fix/name
  src/components/DetailPage/AddressChange/AddressChange.jsx
  src/components/DetailPage/AddressChange/addressChange.styled.js
  src/pages/DetailPage/DetailPage.jsx
  src/pages/DetailPage/detailPage.styled.js
Labels: bug

#94 [Fead/Modify] header cart번튼 추가 및 스타일 변경
  src/components/common/CategorySelect/categorySelector.styled.js
  src/components/common/Header/Header.jsx
  src/components/common/Header/header.styled.js
Labels: enhancement, feat

#95 [Modify] 라디오버튼 및 필터페이지 모바일크기 수정
  src/components/MainPage/ChoiceBook/ChoiceBook.styled.js
  src/pages/FilteredPage/filteredPage.styled.js
  src/pages/ResultPage/ResultPage.styled.js
Labels: feat

#96 Feat/address change
  src/components/DetailPage/AddressChange/AddressChange.jsx
  src/components/DetailPage/DeliveryEstimate/DeliveryEstimate.jsx
  src/components/DetailPage/QuantitySelector/QuantitySelector.jsx
  src/components/DetailPage/QuantitySelector/QuantitySelector.styled.js
  src/components/DetailPage/ScrollToTopButton/ScrollToTopButton.jsx
  src/layout/AppLayout.jsx
  src/pages/DetailPage/DetailPage.jsx
  src/pages/DetailPage/detailPage.styled.js
Labels: enhancement, feat

#98 [Modify] 메인 레이아웃 스타일 수정
  src/components/MainPage/Banner/banner.styled.js
  src/components/MainPage/BestsellerBook/bestsellerBook.styled.js
  src/components/MainPage/BestsellerBook/bestsellerBookSlider.styled.js
  src/components/MainPage/ChoiceBook/ChoiceBook.styled.js
  src/components/MainPage/ChoiceBook/ChoiceBookSlider.styled.js
  src/components/common/Loading/loading.styled.js
  src/pages/CartPage/CartPage.styled.js
Labels: enhancement

#102 [Modify] 스타일 수정
  src/components/FilteredPage/bookCard.styled.js
  src/components/MainPage/NewBook/NewBookCard.jsx
  src/components/MainPage/NewBook/NewBookCard.styled.js
  src/components/MainPage/NewBook/NewBookSlider.styled.js
  src/pages/FilteredPage/filteredPage.styled.js
Labels: enhancement
